package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightAmberTheme =
    lightColorScheme(
        primary = Color(0xFF785900),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDF9E),
        onPrimaryContainer = Color(0xFF261A00),
        secondary = Color(0xFF6B5D3F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF5E0BB),
        onSecondaryContainer = Color(0xFF241A04),
        tertiary = Color(0xFF4A6547),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCCEBC4),
        onTertiaryContainer = Color(0xFF072109),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F2),
        onBackground = Color(0xFF1E1B16),
        surface = Color(0xFFFFF8F2),
        onSurface = Color(0xFF1E1B16),
        surfaceContainer = Color(0xFFF5EDE4),
        surfaceContainerLow = Color(0xFFFAF2E9),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFEFE7DE),
        surfaceContainerHighest = Color(0xFFE9E1D8),
        surfaceVariant = Color(0xFFE9E1D8),
        onSurfaceVariant = Color(0xFF4A4640),
        outline = Color(0xFF7C766F),
        outlineVariant = Color(0xFFCCC5BD),
        inverseOnSurface = Color(0xFFF7EFE7),
        inverseSurface = Color(0xFF33302A),
        inversePrimary = Color(0xFFFABD00),
        surfaceBright = Color(0xFFFFF8F2),
        surfaceDim = Color(0xFFE0D9D0),
        primaryFixed = Color(0xFFFFDF9E),
        primaryFixedDim = Color(0xFFFABD00),
        onPrimaryFixed = Color(0xFF261A00),
        onPrimaryFixedVariant = Color(0xFF5B4300),
        secondaryFixed = Color(0xFFF5E0BB),
        secondaryFixedDim = Color(0xFFD8C4A0),
        onSecondaryFixed = Color(0xFF241A04),
        onSecondaryFixedVariant = Color(0xFF52452A),
        tertiaryFixed = Color(0xFFCCEBC4),
        tertiaryFixedDim = Color(0xFFB0CFAA),
        onTertiaryFixed = Color(0xFF072109),
        onTertiaryFixedVariant = Color(0xFF334D31),
    )

val DarkAmberTheme =
    darkColorScheme(
        primary = Color(0xFFFABD00),
        onPrimary = Color(0xFF3F2E00),
        primaryContainer = Color(0xFF5B4300),
        onPrimaryContainer = Color(0xFFFFDF9E),
        secondary = Color(0xFFD8C4A0),
        onSecondary = Color(0xFF3A2F15),
        secondaryContainer = Color(0xFF52452A),
        onSecondaryContainer = Color(0xFFF5E0BB),
        tertiary = Color(0xFFB0CFAA),
        onTertiary = Color(0xFF1D361C),
        tertiaryContainer = Color(0xFF334D31),
        onTertiaryContainer = Color(0xFFCCEBC4),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF16130E),
        onBackground = Color(0xFFE9E1D8),
        surface = Color(0xFF16130E),
        onSurface = Color(0xFFE9E1D8),
        surfaceContainer = Color(0xFF221F1A),
        surfaceContainerLow = Color(0xFF1E1B16),
        surfaceContainerLowest = Color(0xFF100E09),
        surfaceContainerHigh = Color(0xFF2D2924),
        surfaceContainerHighest = Color(0xFF38342E),
        surfaceVariant = Color(0xFF4A4640),
        onSurfaceVariant = Color(0xFFCCC5BD),
        outline = Color(0xFF969088),
        outlineVariant = Color(0xFF4A4640),
        inverseOnSurface = Color(0xFF33302A),
        inverseSurface = Color(0xFFE9E1D8),
        inversePrimary = Color(0xFF785900),
        surfaceBright = Color(0xFF3C3933),
        surfaceDim = Color(0xFF16130E),
        primaryFixed = Color(0xFFFFDF9E),
        primaryFixedDim = Color(0xFFFABD00),
        onPrimaryFixed = Color(0xFF261A00),
        onPrimaryFixedVariant = Color(0xFF5B4300),
        secondaryFixed = Color(0xFFF5E0BB),
        secondaryFixedDim = Color(0xFFD8C4A0),
        onSecondaryFixed = Color(0xFF241A04),
        onSecondaryFixedVariant = Color(0xFF52452A),
        tertiaryFixed = Color(0xFFCCEBC4),
        tertiaryFixedDim = Color(0xFFB0CFAA),
        onTertiaryFixed = Color(0xFF072109),
        onTertiaryFixedVariant = Color(0xFF334D31),
    )
