package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightBlueTheme =
    lightColorScheme(
        primary = Color(0xFF0061A4),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD1E4FF),
        onPrimaryContainer = Color(0xFF001D36),
        secondary = Color(0xFF535F70),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD7E3F7),
        onSecondaryContainer = Color(0xFF101C2B),
        tertiary = Color(0xFF6B5778),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF2DAFF),
        onTertiaryContainer = Color(0xFF251431),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFAF9FC),
        onBackground = Color(0xFF1A1C1E),
        surface = Color(0xFFFAF9FC),
        onSurface = Color(0xFF1A1C1E),
        surfaceContainer = Color(0xFFEEEDF1),
        surfaceContainerLow = Color(0xFFF4F3F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE8E8EB),
        surfaceContainerHighest = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFFE2E2E6),
        onSurfaceVariant = Color(0xFF45474A),
        outline = Color(0xFF76777A),
        outlineVariant = Color(0xFFC6C6CA),
        inverseOnSurface = Color(0xFFF1F0F4),
        inverseSurface = Color(0xFF2F3033),
        inversePrimary = Color(0xFF9ECAFF),
        surfaceBright = Color(0xFFFAF9FC),
        surfaceDim = Color(0xFFDADADD),
        primaryFixed = Color(0xFFD1E4FF),
        primaryFixedDim = Color(0xFF9ECAFF),
        onPrimaryFixed = Color(0xFF001D36),
        onPrimaryFixedVariant = Color(0xFF00497D),
        secondaryFixed = Color(0xFFD7E3F7),
        secondaryFixedDim = Color(0xFFBBC7DB),
        onSecondaryFixed = Color(0xFF101C2B),
        onSecondaryFixedVariant = Color(0xFF3B4858),
        tertiaryFixed = Color(0xFFF2DAFF),
        tertiaryFixedDim = Color(0xFFD6BEE4),
        onTertiaryFixed = Color(0xFF251431),
        onTertiaryFixedVariant = Color(0xFF523F5F),
    )

val DarkBlueTheme =
    darkColorScheme(
        primary = Color(0xFF9ECAFF),
        onPrimary = Color(0xFF003258),
        primaryContainer = Color(0xFF00497D),
        onPrimaryContainer = Color(0xFFD1E4FF),
        secondary = Color(0xFFBBC7DB),
        onSecondary = Color(0xFF253140),
        secondaryContainer = Color(0xFF3B4858),
        onSecondaryContainer = Color(0xFFD7E3F7),
        tertiary = Color(0xFFD6BEE4),
        onTertiary = Color(0xFF3B2948),
        tertiaryContainer = Color(0xFF523F5F),
        onTertiaryContainer = Color(0xFFF2DAFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF121316),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF121316),
        onSurface = Color(0xFFE2E2E6),
        surfaceContainer = Color(0xFF1E2022),
        surfaceContainerLow = Color(0xFF1A1C1E),
        surfaceContainerLowest = Color(0xFF0D0E11),
        surfaceContainerHigh = Color(0xFF282A2D),
        surfaceContainerHighest = Color(0xFF333538),
        surfaceVariant = Color(0xFF45474A),
        onSurfaceVariant = Color(0xFFC6C6CA),
        outline = Color(0xFF909094),
        outlineVariant = Color(0xFF45474A),
        inverseOnSurface = Color(0xFF2F3033),
        inverseSurface = Color(0xFFE2E2E6),
        inversePrimary = Color(0xFF0061A4),
        surfaceBright = Color(0xFF38393C),
        surfaceDim = Color(0xFF121316),
        primaryFixed = Color(0xFFD1E4FF),
        primaryFixedDim = Color(0xFF9ECAFF),
        onPrimaryFixed = Color(0xFF001D36),
        onPrimaryFixedVariant = Color(0xFF00497D),
        secondaryFixed = Color(0xFFD7E3F7),
        secondaryFixedDim = Color(0xFFBBC7DB),
        onSecondaryFixed = Color(0xFF101C2B),
        onSecondaryFixedVariant = Color(0xFF3B4858),
        tertiaryFixed = Color(0xFFF2DAFF),
        tertiaryFixedDim = Color(0xFFD6BEE4),
        onTertiaryFixed = Color(0xFF251431),
        onTertiaryFixedVariant = Color(0xFF523F5F),
    )
