package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightBlueGreyTheme =
    lightColorScheme(
        primary = Color(0xFF00668A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFC4E7FF),
        onPrimaryContainer = Color(0xFF001E2C),
        secondary = Color(0xFF4E616D),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD1E5F4),
        onSecondaryContainer = Color(0xFF0A1E28),
        tertiary = Color(0xFF605A7D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE6DEFF),
        onTertiaryContainer = Color(0xFF1D1736),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF8F9FC),
        onBackground = Color(0xFF191C1E),
        surface = Color(0xFFF8F9FC),
        onSurface = Color(0xFF191C1E),
        surfaceContainer = Color(0xFFEDEEF0),
        surfaceContainerLow = Color(0xFFF3F3F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE7E8EA),
        surfaceContainerHighest = Color(0xFFE1E2E5),
        surfaceVariant = Color(0xFFE1E2E5),
        onSurfaceVariant = Color(0xFF454749),
        outline = Color(0xFF757779),
        outlineVariant = Color(0xFFC5C6C9),
        inverseOnSurface = Color(0xFFF0F1F3),
        inverseSurface = Color(0xFF2E3133),
        inversePrimary = Color(0xFF7BD0FF),
        surfaceBright = Color(0xFFF8F9FC),
        surfaceDim = Color(0xFFD9DADC),
        primaryFixed = Color(0xFFC4E7FF),
        primaryFixedDim = Color(0xFF7BD0FF),
        onPrimaryFixed = Color(0xFF001E2C),
        onPrimaryFixedVariant = Color(0xFF004C69),
        secondaryFixed = Color(0xFFD1E5F4),
        secondaryFixedDim = Color(0xFFB5C9D7),
        onSecondaryFixed = Color(0xFF0A1E28),
        onSecondaryFixedVariant = Color(0xFF374955),
        tertiaryFixed = Color(0xFFE6DEFF),
        tertiaryFixedDim = Color(0xFFCAC1E9),
        onTertiaryFixed = Color(0xFF1D1736),
        onTertiaryFixedVariant = Color(0xFF484264),
    )

val DarkBlueGreyTheme =
    darkColorScheme(
        primary = Color(0xFF7BD0FF),
        onPrimary = Color(0xFF003549),
        primaryContainer = Color(0xFF004C69),
        onPrimaryContainer = Color(0xFFC4E7FF),
        secondary = Color(0xFFB5C9D7),
        onSecondary = Color(0xFF20333E),
        secondaryContainer = Color(0xFF374955),
        onSecondaryContainer = Color(0xFFD1E5F4),
        tertiary = Color(0xFFCAC1E9),
        onTertiary = Color(0xFF322C4C),
        tertiaryContainer = Color(0xFF484264),
        onTertiaryContainer = Color(0xFFE6DEFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF111416),
        onBackground = Color(0xFFE1E2E5),
        surface = Color(0xFF111416),
        onSurface = Color(0xFFE1E2E5),
        surfaceContainer = Color(0xFF1D2022),
        surfaceContainerLow = Color(0xFF191C1E),
        surfaceContainerLowest = Color(0xFF0C0F10),
        surfaceContainerHigh = Color(0xFF282A2C),
        surfaceContainerHighest = Color(0xFF333537),
        surfaceVariant = Color(0xFF454749),
        onSurfaceVariant = Color(0xFFC5C6C9),
        outline = Color(0xFF8F9193),
        outlineVariant = Color(0xFF454749),
        inverseOnSurface = Color(0xFF2E3133),
        inverseSurface = Color(0xFFE1E2E5),
        inversePrimary = Color(0xFF00668A),
        surfaceBright = Color(0xFF37393C),
        surfaceDim = Color(0xFF111416),
        primaryFixed = Color(0xFFC4E7FF),
        primaryFixedDim = Color(0xFF7BD0FF),
        onPrimaryFixed = Color(0xFF001E2C),
        onPrimaryFixedVariant = Color(0xFF004C69),
        secondaryFixed = Color(0xFFD1E5F4),
        secondaryFixedDim = Color(0xFFB5C9D7),
        onSecondaryFixed = Color(0xFF0A1E28),
        onSecondaryFixedVariant = Color(0xFF374955),
        tertiaryFixed = Color(0xFFE6DEFF),
        tertiaryFixedDim = Color(0xFFCAC1E9),
        onTertiaryFixed = Color(0xFF1D1736),
        onTertiaryFixedVariant = Color(0xFF484264),
    )
