package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightBrownTheme =
    lightColorScheme(
        primary = Color(0xFF9A4522),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBCF),
        onPrimaryContainer = Color(0xFF380D00),
        secondary = Color(0xFF77574C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDBCF),
        onSecondaryContainer = Color(0xFF2C160D),
        tertiary = Color(0xFF695E2F),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF2E2A8),
        onTertiaryContainer = Color(0xFF211B00),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF201A18),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF201A18),
        surfaceContainer = Color(0xFFF8EBE7),
        surfaceContainerLow = Color(0xFFFEF1ED),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF3E5E2),
        surfaceContainerHighest = Color(0xFFEDE0DC),
        surfaceVariant = Color(0xFFEDE0DC),
        onSurfaceVariant = Color(0xFF4D4542),
        outline = Color(0xFF7F7572),
        outlineVariant = Color(0xFFD0C4C0),
        inverseOnSurface = Color(0xFFFBEEEA),
        inverseSurface = Color(0xFF362F2C),
        inversePrimary = Color(0xFFFFB59A),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceDim = Color(0xFFE4D7D4),
        primaryFixed = Color(0xFFFFDBCF),
        primaryFixedDim = Color(0xFFFFB59A),
        onPrimaryFixed = Color(0xFF380D00),
        onPrimaryFixedVariant = Color(0xFF7B2E0D),
        secondaryFixed = Color(0xFFFFDBCF),
        secondaryFixedDim = Color(0xFFE7BEAF),
        onSecondaryFixed = Color(0xFF2C160D),
        onSecondaryFixedVariant = Color(0xFF5D4035),
        tertiaryFixed = Color(0xFFF2E2A8),
        tertiaryFixedDim = Color(0xFFD5C68E),
        onTertiaryFixed = Color(0xFF211B00),
        onTertiaryFixedVariant = Color(0xFF50471A),
    )

val DarkBrownTheme =
    darkColorScheme(
        primary = Color(0xFFFFB59A),
        onPrimary = Color(0xFF5B1B00),
        primaryContainer = Color(0xFF7B2E0D),
        onPrimaryContainer = Color(0xFFFFDBCF),
        secondary = Color(0xFFE7BEAF),
        onSecondary = Color(0xFF442A20),
        secondaryContainer = Color(0xFF5D4035),
        onSecondaryContainer = Color(0xFFFFDBCF),
        tertiary = Color(0xFFD5C68E),
        onTertiary = Color(0xFF393005),
        tertiaryContainer = Color(0xFF50471A),
        onTertiaryContainer = Color(0xFFF2E2A8),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF181210),
        onBackground = Color(0xFFEDE0DC),
        surface = Color(0xFF181210),
        onSurface = Color(0xFFEDE0DC),
        surfaceContainer = Color(0xFF251E1C),
        surfaceContainerLow = Color(0xFF201A18),
        surfaceContainerLowest = Color(0xFF120D0B),
        surfaceContainerHigh = Color(0xFF2F2826),
        surfaceContainerHighest = Color(0xFF3B3331),
        surfaceVariant = Color(0xFF4D4542),
        onSurfaceVariant = Color(0xFFD0C4C0),
        outline = Color(0xFF998E8B),
        outlineVariant = Color(0xFF4D4542),
        inverseOnSurface = Color(0xFF362F2C),
        inverseSurface = Color(0xFFEDE0DC),
        inversePrimary = Color(0xFF9A4522),
        surfaceBright = Color(0xFF3F3835),
        surfaceDim = Color(0xFF181210),
        primaryFixed = Color(0xFFFFDBCF),
        primaryFixedDim = Color(0xFFFFB59A),
        onPrimaryFixed = Color(0xFF380D00),
        onPrimaryFixedVariant = Color(0xFF7B2E0D),
        secondaryFixed = Color(0xFFFFDBCF),
        secondaryFixedDim = Color(0xFFE7BEAF),
        onSecondaryFixed = Color(0xFF2C160D),
        onSecondaryFixedVariant = Color(0xFF5D4035),
        tertiaryFixed = Color(0xFFF2E2A8),
        tertiaryFixedDim = Color(0xFFD5C68E),
        onTertiaryFixed = Color(0xFF211B00),
        onTertiaryFixedVariant = Color(0xFF50471A),
    )
