package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightCyanTheme =
    lightColorScheme(
        primary = Color(0xFF006876),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA1EFFF),
        onPrimaryContainer = Color(0xFF001F25),
        secondary = Color(0xFF4A6268),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCDE7ED),
        onSecondaryContainer = Color(0xFF051F23),
        tertiary = Color(0xFF545D7E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFDBE1FF),
        onTertiaryContainer = Color(0xFF101A37),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF8FAFA),
        onBackground = Color(0xFF191C1D),
        surface = Color(0xFFF8FAFA),
        onSurface = Color(0xFF191C1D),
        surfaceContainer = Color(0xFFECEEEF),
        surfaceContainerLow = Color(0xFFF2F4F4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE6E8E9),
        surfaceContainerHighest = Color(0xFFE1E3E3),
        surfaceVariant = Color(0xFFE1E3E3),
        onSurfaceVariant = Color(0xFF444748),
        outline = Color(0xFF747778),
        outlineVariant = Color(0xFFC4C7C8),
        inverseOnSurface = Color(0xFFEFF1F2),
        inverseSurface = Color(0xFF2E3132),
        inversePrimary = Color(0xFF44D8F1),
        surfaceBright = Color(0xFFF8FAFA),
        surfaceDim = Color(0xFFD8DADB),
        primaryFixed = Color(0xFFA1EFFF),
        primaryFixedDim = Color(0xFF44D8F1),
        onPrimaryFixed = Color(0xFF001F25),
        onPrimaryFixedVariant = Color(0xFF004E59),
        secondaryFixed = Color(0xFFCDE7ED),
        secondaryFixedDim = Color(0xFFB1CBD1),
        onSecondaryFixed = Color(0xFF051F23),
        onSecondaryFixedVariant = Color(0xFF334A50),
        tertiaryFixed = Color(0xFFDBE1FF),
        tertiaryFixedDim = Color(0xFFBCC5EB),
        onTertiaryFixed = Color(0xFF101A37),
        onTertiaryFixedVariant = Color(0xFF3C4665),
    )

val DarkCyanTheme =
    darkColorScheme(
        primary = Color(0xFF44D8F1),
        onPrimary = Color(0xFF00363E),
        primaryContainer = Color(0xFF004E59),
        onPrimaryContainer = Color(0xFFA1EFFF),
        secondary = Color(0xFFB1CBD1),
        onSecondary = Color(0xFF1C3439),
        secondaryContainer = Color(0xFF334A50),
        onSecondaryContainer = Color(0xFFCDE7ED),
        tertiary = Color(0xFFBCC5EB),
        onTertiary = Color(0xFF262F4D),
        tertiaryContainer = Color(0xFF3C4665),
        onTertiaryContainer = Color(0xFFDBE1FF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF111415),
        onBackground = Color(0xFFE1E3E3),
        surface = Color(0xFF111415),
        onSurface = Color(0xFFE1E3E3),
        surfaceContainer = Color(0xFF1D2021),
        surfaceContainerLow = Color(0xFF191C1D),
        surfaceContainerLowest = Color(0xFF0B0F10),
        surfaceContainerHigh = Color(0xFF272B2B),
        surfaceContainerHighest = Color(0xFF323536),
        surfaceVariant = Color(0xFF444748),
        onSurfaceVariant = Color(0xFFC4C7C8),
        outline = Color(0xFF8E9192),
        outlineVariant = Color(0xFF444748),
        inverseOnSurface = Color(0xFF2E3132),
        inverseSurface = Color(0xFFE1E3E3),
        inversePrimary = Color(0xFF006876),
        surfaceBright = Color(0xFF363A3B),
        surfaceDim = Color(0xFF111415),
        primaryFixed = Color(0xFFA1EFFF),
        primaryFixedDim = Color(0xFF44D8F1),
        onPrimaryFixed = Color(0xFF001F25),
        onPrimaryFixedVariant = Color(0xFF004E59),
        secondaryFixed = Color(0xFFCDE7ED),
        secondaryFixedDim = Color(0xFFB1CBD1),
        onSecondaryFixed = Color(0xFF051F23),
        onSecondaryFixedVariant = Color(0xFF334A50),
        tertiaryFixed = Color(0xFFDBE1FF),
        tertiaryFixedDim = Color(0xFFBCC5EB),
        onTertiaryFixed = Color(0xFF101A37),
        onTertiaryFixedVariant = Color(0xFF3C4665),
    )
