package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightDeepPurpleTheme =
    lightColorScheme(
        primary = Color(0xFF6F43C0),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEBDDFF),
        onPrimaryContainer = Color(0xFF250059),
        secondary = Color(0xFF635B70),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE9DEF8),
        onSecondaryContainer = Color(0xFF1F182B),
        tertiary = Color(0xFF7E525D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9E1),
        onTertiaryContainer = Color(0xFF31101B),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFEF8FD),
        onBackground = Color(0xFF1D1B1E),
        surface = Color(0xFFFEF8FD),
        onSurface = Color(0xFF1D1B1E),
        surfaceContainer = Color(0xFFF2ECF1),
        surfaceContainerLow = Color(0xFFF8F2F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFECE6EB),
        surfaceContainerHighest = Color(0xFFE6E1E6),
        surfaceVariant = Color(0xFFE6E1E6),
        onSurfaceVariant = Color(0xFF48464A),
        outline = Color(0xFF79767A),
        outlineVariant = Color(0xFFCAC5CA),
        inverseOnSurface = Color(0xFFF5EFF4),
        inverseSurface = Color(0xFF323033),
        inversePrimary = Color(0xFFD3BBFF),
        surfaceBright = Color(0xFFFEF8FD),
        surfaceDim = Color(0xFFDED8DD),
        primaryFixed = Color(0xFFEBDDFF),
        primaryFixedDim = Color(0xFFD3BBFF),
        onPrimaryFixed = Color(0xFF250059),
        onPrimaryFixedVariant = Color(0xFF5727A6),
        secondaryFixed = Color(0xFFE9DEF8),
        secondaryFixedDim = Color(0xFFCDC2DB),
        onSecondaryFixed = Color(0xFF1F182B),
        onSecondaryFixedVariant = Color(0xFF4B4358),
        tertiaryFixed = Color(0xFFFFD9E1),
        tertiaryFixedDim = Color(0xFFF0B7C5),
        onTertiaryFixed = Color(0xFF31101B),
        onTertiaryFixedVariant = Color(0xFF643B46),
    )

val DarkDeepPurpleTheme =
    darkColorScheme(
        primary = Color(0xFFD3BBFF),
        onPrimary = Color(0xFF3F008D),
        primaryContainer = Color(0xFF5727A6),
        onPrimaryContainer = Color(0xFFEBDDFF),
        secondary = Color(0xFFCDC2DB),
        onSecondary = Color(0xFF342D40),
        secondaryContainer = Color(0xFF4B4358),
        onSecondaryContainer = Color(0xFFE9DEF8),
        tertiary = Color(0xFFF0B7C5),
        onTertiary = Color(0xFF4A2530),
        tertiaryContainer = Color(0xFF643B46),
        onTertiaryContainer = Color(0xFFFFD9E1),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF141316),
        onBackground = Color(0xFFE6E1E6),
        surface = Color(0xFF141316),
        onSurface = Color(0xFFE6E1E6),
        surfaceContainer = Color(0xFF211F22),
        surfaceContainerLow = Color(0xFF1D1B1E),
        surfaceContainerLowest = Color(0xFF0F0E11),
        surfaceContainerHigh = Color(0xFF2B292D),
        surfaceContainerHighest = Color(0xFF363438),
        surfaceVariant = Color(0xFF48464A),
        onSurfaceVariant = Color(0xFFCAC5CA),
        outline = Color(0xFF938F94),
        outlineVariant = Color(0xFF48464A),
        inverseOnSurface = Color(0xFF323033),
        inverseSurface = Color(0xFFE6E1E6),
        inversePrimary = Color(0xFF6F43C0),
        surfaceBright = Color(0xFF3B383C),
        surfaceDim = Color(0xFF141316),
        primaryFixed = Color(0xFFEBDDFF),
        primaryFixedDim = Color(0xFFD3BBFF),
        onPrimaryFixed = Color(0xFF250059),
        onPrimaryFixedVariant = Color(0xFF5727A6),
        secondaryFixed = Color(0xFFE9DEF8),
        secondaryFixedDim = Color(0xFFCDC2DB),
        onSecondaryFixed = Color(0xFF1F182B),
        onSecondaryFixedVariant = Color(0xFF4B4358),
        tertiaryFixed = Color(0xFFFFD9E1),
        tertiaryFixedDim = Color(0xFFF0B7C5),
        onTertiaryFixed = Color(0xFF31101B),
        onTertiaryFixedVariant = Color(0xFF643B46),
    )
