package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightDeepOrangeTheme =
    lightColorScheme(
        primary = Color(0xFFB02F00),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBD1),
        onPrimaryContainer = Color(0xFF3B0900),
        secondary = Color(0xFF77574E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDBD1),
        onSecondaryContainer = Color(0xFF2C150F),
        tertiary = Color(0xFF6C5D2F),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF5E1A7),
        onTertiaryContainer = Color(0xFF231B00),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF201A18),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF201A18),
        surfaceContainer = Color(0xFFF8EBE8),
        surfaceContainerLow = Color(0xFFFEF1ED),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF3E5E2),
        surfaceContainerHighest = Color(0xFFEDE0DC),
        surfaceVariant = Color(0xFFEDE0DC),
        onSurfaceVariant = Color(0xFF4D4543),
        outline = Color(0xFF7F7572),
        outlineVariant = Color(0xFFD0C4C1),
        inverseOnSurface = Color(0xFFFBEEEB),
        inverseSurface = Color(0xFF362F2D),
        inversePrimary = Color(0xFFFFB5A0),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceDim = Color(0xFFE4D7D4),
        primaryFixed = Color(0xFFFFDBD1),
        primaryFixedDim = Color(0xFFFFB5A0),
        onPrimaryFixed = Color(0xFF3B0900),
        onPrimaryFixedVariant = Color(0xFF862200),
        secondaryFixed = Color(0xFFFFDBD1),
        secondaryFixedDim = Color(0xFFE7BDB2),
        onSecondaryFixed = Color(0xFF2C150F),
        onSecondaryFixedVariant = Color(0xFF5D4037),
        tertiaryFixed = Color(0xFFF5E1A7),
        tertiaryFixedDim = Color(0xFFD8C58D),
        onTertiaryFixed = Color(0xFF231B00),
        onTertiaryFixedVariant = Color(0xFF534619),
    )

val DarkDeepOrangeTheme =
    darkColorScheme(
        primary = Color(0xFFFFB5A0),
        onPrimary = Color(0xFF5F1500),
        primaryContainer = Color(0xFF862200),
        onPrimaryContainer = Color(0xFFFFDBD1),
        secondary = Color(0xFFE7BDB2),
        onSecondary = Color(0xFF442A22),
        secondaryContainer = Color(0xFF5D4037),
        onSecondaryContainer = Color(0xFFFFDBD1),
        tertiary = Color(0xFFD8C58D),
        onTertiary = Color(0xFF3B2F05),
        tertiaryContainer = Color(0xFF534619),
        onTertiaryContainer = Color(0xFFF5E1A7),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF181210),
        onBackground = Color(0xFFEDE0DC),
        surface = Color(0xFF181210),
        onSurface = Color(0xFFEDE0DC),
        surfaceContainer = Color(0xFF251E1C),
        surfaceContainerLow = Color(0xFF201A18),
        surfaceContainerLowest = Color(0xFF120D0B),
        surfaceContainerHigh = Color(0xFF2F2827),
        surfaceContainerHighest = Color(0xFF3B3331),
        surfaceVariant = Color(0xFF4D4543),
        onSurfaceVariant = Color(0xFFD0C4C1),
        outline = Color(0xFF998E8C),
        outlineVariant = Color(0xFF4D4543),
        inverseOnSurface = Color(0xFF362F2D),
        inverseSurface = Color(0xFFEDE0DC),
        inversePrimary = Color(0xFFB02F00),
        surfaceBright = Color(0xFF3F3735),
        surfaceDim = Color(0xFF181210),
        primaryFixed = Color(0xFFFFDBD1),
        primaryFixedDim = Color(0xFFFFB5A0),
        onPrimaryFixed = Color(0xFF3B0900),
        onPrimaryFixedVariant = Color(0xFF862200),
        secondaryFixed = Color(0xFFFFDBD1),
        secondaryFixedDim = Color(0xFFE7BDB2),
        onSecondaryFixed = Color(0xFF2C150F),
        onSecondaryFixedVariant = Color(0xFF5D4037),
        tertiaryFixed = Color(0xFFF5E1A7),
        tertiaryFixedDim = Color(0xFFD8C58D),
        onTertiaryFixed = Color(0xFF231B00),
        onTertiaryFixedVariant = Color(0xFF534619),
    )
