package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF68548E)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFEBDDFF)
private val onPrimaryContainerLight = Color(0xFF4F3D74)
private val secondaryLight = Color(0xFF635B70)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFE9DEF8)
private val onSecondaryContainerLight = Color(0xFF4B4358)
private val tertiaryLight = Color(0xFF7E525D)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFD9E1)
private val onTertiaryContainerLight = Color(0xFF643B46)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFEF7FF)
private val onBackgroundLight = Color(0xFF1D1B20)
private val surfaceLight = Color(0xFFFEF7FF)
private val onSurfaceLight = Color(0xFF1D1B20)
private val surfaceVariantLight = Color(0xFFE7E0EB)
private val onSurfaceVariantLight = Color(0xFF49454E)
private val outlineLight = Color(0xFF7A757F)
private val outlineVariantLight = Color(0xFFCBC4CF)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF322F35)
private val inverseOnSurfaceLight = Color(0xFFF5EFF7)
private val inversePrimaryLight = Color(0xFFD3BCFD)
private val surfaceDimLight = Color(0xFFDED8E0)
private val surfaceBrightLight = Color(0xFFFEF7FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF8F1FA)
private val surfaceContainerLight = Color(0xFFF2ECF4)
private val surfaceContainerHighLight = Color(0xFFEDE6EE)
private val surfaceContainerHighestLight = Color(0xFFE7E0E8)

private val primaryLightHighContrast = Color(0xFF342157)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF523F77)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF30293C)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF4D465A)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF45212C)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF673D48)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFEF7FF)
private val onBackgroundLightHighContrast = Color(0xFF1D1B20)
private val surfaceLightHighContrast = Color(0xFFFEF7FF)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE7E0EB)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF2E2B33)
private val outlineVariantLightHighContrast = Color(0xFF4C4751)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF322F35)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFD3BCFD)
private val surfaceDimLightHighContrast = Color(0xFFBCB7BF)
private val surfaceBrightLightHighContrast = Color(0xFFFEF7FF)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF5EFF7)
private val surfaceContainerLightHighContrast = Color(0xFFE7E0E8)
private val surfaceContainerHighLightHighContrast = Color(0xFFD8D2DA)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCAC4CC)

private val primaryDark = Color(0xFFD3BCFD)
private val onPrimaryDark = Color(0xFF38265C)
private val primaryContainerDark = Color(0xFF4F3D74)
private val onPrimaryContainerDark = Color(0xFFEBDDFF)
private val secondaryDark = Color(0xFFCDC2DB)
private val onSecondaryDark = Color(0xFF342D40)
private val secondaryContainerDark = Color(0xFF4B4358)
private val onSecondaryContainerDark = Color(0xFFE9DEF8)
private val tertiaryDark = Color(0xFFF0B7C5)
private val onTertiaryDark = Color(0xFF4A2530)
private val tertiaryContainerDark = Color(0xFF643B46)
private val onTertiaryContainerDark = Color(0xFFFFD9E1)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF151218)
private val onBackgroundDark = Color(0xFFE7E0E8)
private val surfaceDark = Color(0xFF151218)
private val onSurfaceDark = Color(0xFFE7E0E8)
private val surfaceVariantDark = Color(0xFF49454E)
private val onSurfaceVariantDark = Color(0xFFCBC4CF)
private val outlineDark = Color(0xFF948F99)
private val outlineVariantDark = Color(0xFF49454E)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE7E0E8)
private val inverseOnSurfaceDark = Color(0xFF322F35)
private val inversePrimaryDark = Color(0xFF68548E)
private val surfaceDimDark = Color(0xFF151218)
private val surfaceBrightDark = Color(0xFF3B383E)
private val surfaceContainerLowestDark = Color(0xFF0F0D13)
private val surfaceContainerLowDark = Color(0xFF1D1B20)
private val surfaceContainerDark = Color(0xFF211F24)
private val surfaceContainerHighDark = Color(0xFF2C292F)
private val surfaceContainerHighestDark = Color(0xFF36343A)

private val primaryDarkHighContrast = Color(0xFFF6ECFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFCFB8F9)
private val onPrimaryContainerDarkHighContrast = Color(0xFF110031)
private val secondaryDarkHighContrast = Color(0xFFF6ECFF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFC9BED7)
private val onSecondaryContainerDarkHighContrast = Color(0xFF0E0819)
private val tertiaryDarkHighContrast = Color(0xFFFFEBEE)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFECB4C1)
private val onTertiaryContainerDarkHighContrast = Color(0xFF1D020B)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF151218)
private val onBackgroundDarkHighContrast = Color(0xFFE7E0E8)
private val surfaceDarkHighContrast = Color(0xFF151218)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF49454E)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFF5EDF9)
private val outlineVariantDarkHighContrast = Color(0xFFC7C0CB)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE7E0E8)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF513E75)
private val surfaceDimDarkHighContrast = Color(0xFF151218)
private val surfaceBrightDarkHighContrast = Color(0xFF524F55)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF211F24)
private val surfaceContainerDarkHighContrast = Color(0xFF322F35)
private val surfaceContainerHighDarkHighContrast = Color(0xFF3D3A40)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF49454C)

val LightDeepPurpleTheme =
    lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

val DarkDeepPurpleTheme =
    darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

val HighContrastLightDeepPurpleTheme =
    lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

val HighContrastDarkDeepPurpleTheme =
    darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
