package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightGreenTheme =
    lightColorScheme(
        primary = Color(0xFF006E1A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF96F990),
        onPrimaryContainer = Color(0xFF002203),
        secondary = Color(0xFF53634F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD6E8CE),
        onSecondaryContainer = Color(0xFF111F0F),
        tertiary = Color(0xFF38656A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBCEBF0),
        onTertiaryContainer = Color(0xFF002023),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF9FAF3),
        onBackground = Color(0xFF1A1C19),
        surface = Color(0xFFF9FAF3),
        onSurface = Color(0xFF1A1C19),
        surfaceContainer = Color(0xFFEEEEE8),
        surfaceContainerLow = Color(0xFFF3F4EE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE8E9E2),
        surfaceContainerHighest = Color(0xFFE2E3DD),
        surfaceVariant = Color(0xFFE2E3DD),
        onSurfaceVariant = Color(0xFF454743),
        outline = Color(0xFF767873),
        outlineVariant = Color(0xFFC6C7C1),
        inverseOnSurface = Color(0xFFF1F1EB),
        inverseSurface = Color(0xFF2F312D),
        inversePrimary = Color(0xFF7ADC77),
        surfaceBright = Color(0xFFF9FAF3),
        surfaceDim = Color(0xFFDADAD4),
        primaryFixed = Color(0xFF96F990),
        primaryFixedDim = Color(0xFF7ADC77),
        onPrimaryFixed = Color(0xFF002203),
        onPrimaryFixedVariant = Color(0xFF005311),
        secondaryFixed = Color(0xFFD6E8CE),
        secondaryFixedDim = Color(0xFFBACCB3),
        onSecondaryFixed = Color(0xFF111F0F),
        onSecondaryFixedVariant = Color(0xFF3B4B38),
        tertiaryFixed = Color(0xFFBCEBF0),
        tertiaryFixedDim = Color(0xFFA0CFD4),
        onTertiaryFixed = Color(0xFF002023),
        onTertiaryFixedVariant = Color(0xFF1E4D52),
    )

val DarkGreenTheme =
    darkColorScheme(
        primary = Color(0xFF7ADC77),
        onPrimary = Color(0xFF003909),
        primaryContainer = Color(0xFF005311),
        onPrimaryContainer = Color(0xFF96F990),
        secondary = Color(0xFFBACCB3),
        onSecondary = Color(0xFF253423),
        secondaryContainer = Color(0xFF3B4B38),
        onSecondaryContainer = Color(0xFFD6E8CE),
        tertiary = Color(0xFFA0CFD4),
        onTertiary = Color(0xFF00363B),
        tertiaryContainer = Color(0xFF1E4D52),
        onTertiaryContainer = Color(0xFFBCEBF0),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF121411),
        onBackground = Color(0xFFE2E3DD),
        surface = Color(0xFF121411),
        onSurface = Color(0xFFE2E3DD),
        surfaceContainer = Color(0xFF1E201D),
        surfaceContainerLow = Color(0xFF1A1C19),
        surfaceContainerLowest = Color(0xFF0C0F0C),
        surfaceContainerHigh = Color(0xFF282B27),
        surfaceContainerHighest = Color(0xFF333531),
        surfaceVariant = Color(0xFF454743),
        onSurfaceVariant = Color(0xFFC6C7C1),
        outline = Color(0xFF90918C),
        outlineVariant = Color(0xFF454743),
        inverseOnSurface = Color(0xFF2F312D),
        inverseSurface = Color(0xFFE2E3DD),
        inversePrimary = Color(0xFF006E1A),
        surfaceBright = Color(0xFF383A36),
        surfaceDim = Color(0xFF121411),
        primaryFixed = Color(0xFF96F990),
        primaryFixedDim = Color(0xFF7ADC77),
        onPrimaryFixed = Color(0xFF002203),
        onPrimaryFixedVariant = Color(0xFF005311),
        secondaryFixed = Color(0xFFD6E8CE),
        secondaryFixedDim = Color(0xFFBACCB3),
        onSecondaryFixed = Color(0xFF111F0F),
        onSecondaryFixedVariant = Color(0xFF3B4B38),
        tertiaryFixed = Color(0xFFBCEBF0),
        tertiaryFixedDim = Color(0xFFA0CFD4),
        onTertiaryFixed = Color(0xFF002023),
        onTertiaryFixedVariant = Color(0xFF1E4D52),
    )
