package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightIndigoTheme =
    lightColorScheme(
        primary = Color(0xFF4355B9),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDEE0FF),
        onPrimaryContainer = Color(0xFF00105C),
        secondary = Color(0xFF5B5D72),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE0E1F9),
        onSecondaryContainer = Color(0xFF181A2C),
        tertiary = Color(0xFF77536D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD7F1),
        onTertiaryContainer = Color(0xFF2D1228),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFBF8FD),
        onBackground = Color(0xFF1B1B1F),
        surface = Color(0xFFFBF8FD),
        onSurface = Color(0xFF1B1B1F),
        surfaceContainer = Color(0xFFF0EDF1),
        surfaceContainerLow = Color(0xFFF6F2F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFEAE7EC),
        surfaceContainerHighest = Color(0xFFE4E1E6),
        surfaceVariant = Color(0xFFE4E1E6),
        onSurfaceVariant = Color(0xFF47464A),
        outline = Color(0xFF78767A),
        outlineVariant = Color(0xFFC8C5CA),
        inverseOnSurface = Color(0xFFF3F0F4),
        inverseSurface = Color(0xFF303034),
        inversePrimary = Color(0xFFBAC3FF),
        surfaceBright = Color(0xFFFBF8FD),
        surfaceDim = Color(0xFFDCD9DE),
        primaryFixed = Color(0xFFDEE0FF),
        primaryFixedDim = Color(0xFFBAC3FF),
        onPrimaryFixed = Color(0xFF00105C),
        onPrimaryFixedVariant = Color(0xFF293CA0),
        secondaryFixed = Color(0xFFE0E1F9),
        secondaryFixedDim = Color(0xFFC3C5DD),
        onSecondaryFixed = Color(0xFF181A2C),
        onSecondaryFixedVariant = Color(0xFF434659),
        tertiaryFixed = Color(0xFFFFD7F1),
        tertiaryFixedDim = Color(0xFFE6BAD7),
        onTertiaryFixed = Color(0xFF2D1228),
        onTertiaryFixedVariant = Color(0xFF5D3C55),
    )

val DarkIndigoTheme =
    darkColorScheme(
        primary = Color(0xFFBAC3FF),
        onPrimary = Color(0xFF08218A),
        primaryContainer = Color(0xFF293CA0),
        onPrimaryContainer = Color(0xFFDEE0FF),
        secondary = Color(0xFFC3C5DD),
        onSecondary = Color(0xFF2D2F42),
        secondaryContainer = Color(0xFF434659),
        onSecondaryContainer = Color(0xFFE0E1F9),
        tertiary = Color(0xFFE6BAD7),
        onTertiary = Color(0xFF44263D),
        tertiaryContainer = Color(0xFF5D3C55),
        onTertiaryContainer = Color(0xFFFFD7F1),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF131316),
        onBackground = Color(0xFFE4E1E6),
        surface = Color(0xFF131316),
        onSurface = Color(0xFFE4E1E6),
        surfaceContainer = Color(0xFF1F1F23),
        surfaceContainerLow = Color(0xFF1B1B1F),
        surfaceContainerLowest = Color(0xFF0E0E11),
        surfaceContainerHigh = Color(0xFF2A2A2D),
        surfaceContainerHighest = Color(0xFF353438),
        surfaceVariant = Color(0xFF47464A),
        onSurfaceVariant = Color(0xFFC8C5CA),
        outline = Color(0xFF929094),
        outlineVariant = Color(0xFF47464A),
        inverseOnSurface = Color(0xFF303034),
        inverseSurface = Color(0xFFE4E1E6),
        inversePrimary = Color(0xFF4355B9),
        surfaceBright = Color(0xFF39393C),
        surfaceDim = Color(0xFF131316),
        primaryFixed = Color(0xFFDEE0FF),
        primaryFixedDim = Color(0xFFBAC3FF),
        onPrimaryFixed = Color(0xFF00105C),
        onPrimaryFixedVariant = Color(0xFF293CA0),
        secondaryFixed = Color(0xFFE0E1F9),
        secondaryFixedDim = Color(0xFFC3C5DD),
        onSecondaryFixed = Color(0xFF181A2C),
        onSecondaryFixedVariant = Color(0xFF434659),
        tertiaryFixed = Color(0xFFFFD7F1),
        tertiaryFixedDim = Color(0xFFE6BAD7),
        onTertiaryFixed = Color(0xFF2D1228),
        onTertiaryFixedVariant = Color(0xFF5D3C55),
    )
