package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightLightBlueTheme =
    lightColorScheme(
        primary = Color(0xFF006493),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFCAE6FF),
        onPrimaryContainer = Color(0xFF001E30),
        secondary = Color(0xFF50606E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD3E5F5),
        onSecondaryContainer = Color(0xFF0C1D29),
        tertiary = Color(0xFF65587B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFEBDDFF),
        onTertiaryContainer = Color(0xFF201634),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF9F9FC),
        onBackground = Color(0xFF1A1C1E),
        surface = Color(0xFFF9F9FC),
        onSurface = Color(0xFF1A1C1E),
        surfaceContainer = Color(0xFFEDEEF1),
        surfaceContainerLow = Color(0xFFF3F3F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE8E8EB),
        surfaceContainerHighest = Color(0xFFE2E2E5),
        surfaceVariant = Color(0xFFE2E2E5),
        onSurfaceVariant = Color(0xFF454749),
        outline = Color(0xFF75777A),
        outlineVariant = Color(0xFFC6C6C9),
        inverseOnSurface = Color(0xFFF0F0F3),
        inverseSurface = Color(0xFF2E3133),
        inversePrimary = Color(0xFF8DCDFF),
        surfaceBright = Color(0xFFF9F9FC),
        surfaceDim = Color(0xFFD9DADD),
        primaryFixed = Color(0xFFCAE6FF),
        primaryFixedDim = Color(0xFF8DCDFF),
        onPrimaryFixed = Color(0xFF001E30),
        onPrimaryFixedVariant = Color(0xFF004B70),
        secondaryFixed = Color(0xFFD3E5F5),
        secondaryFixedDim = Color(0xFFB7C9D9),
        onSecondaryFixed = Color(0xFF0C1D29),
        onSecondaryFixedVariant = Color(0xFF384956),
        tertiaryFixed = Color(0xFFEBDDFF),
        tertiaryFixedDim = Color(0xFFCFC0E8),
        onTertiaryFixed = Color(0xFF201634),
        onTertiaryFixedVariant = Color(0xFF4D4162),
    )

val DarkLightBlueTheme =
    darkColorScheme(
        primary = Color(0xFF8DCDFF),
        onPrimary = Color(0xFF00344F),
        primaryContainer = Color(0xFF004B70),
        onPrimaryContainer = Color(0xFFCAE6FF),
        secondary = Color(0xFFB7C9D9),
        onSecondary = Color(0xFF22323F),
        secondaryContainer = Color(0xFF384956),
        onSecondaryContainer = Color(0xFFD3E5F5),
        tertiary = Color(0xFFCFC0E8),
        onTertiary = Color(0xFF362B4B),
        tertiaryContainer = Color(0xFF4D4162),
        onTertiaryContainer = Color(0xFFEBDDFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF111416),
        onBackground = Color(0xFFE2E2E5),
        surface = Color(0xFF111416),
        onSurface = Color(0xFFE2E2E5),
        surfaceContainer = Color(0xFF1E2022),
        surfaceContainerLow = Color(0xFF1A1C1E),
        surfaceContainerLowest = Color(0xFF0C0E11),
        surfaceContainerHigh = Color(0xFF282A2D),
        surfaceContainerHighest = Color(0xFF333537),
        surfaceVariant = Color(0xFF454749),
        onSurfaceVariant = Color(0xFFC6C6C9),
        outline = Color(0xFF8F9193),
        outlineVariant = Color(0xFF454749),
        inverseOnSurface = Color(0xFF2E3133),
        inverseSurface = Color(0xFFE2E2E5),
        inversePrimary = Color(0xFF006493),
        surfaceBright = Color(0xFF37393C),
        surfaceDim = Color(0xFF111416),
        primaryFixed = Color(0xFFCAE6FF),
        primaryFixedDim = Color(0xFF8DCDFF),
        onPrimaryFixed = Color(0xFF001E30),
        onPrimaryFixedVariant = Color(0xFF004B70),
        secondaryFixed = Color(0xFFD3E5F5),
        secondaryFixedDim = Color(0xFFB7C9D9),
        onSecondaryFixed = Color(0xFF0C1D29),
        onSecondaryFixedVariant = Color(0xFF384956),
        tertiaryFixed = Color(0xFFEBDDFF),
        tertiaryFixedDim = Color(0xFFCFC0E8),
        onTertiaryFixed = Color(0xFF201634),
        onTertiaryFixedVariant = Color(0xFF4D4162),
    )
