package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightLightGreenTheme =
    lightColorScheme(
        primary = Color(0xFF006C48),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF8DF7C2),
        onPrimaryContainer = Color(0xFF002113),
        secondary = Color(0xFF4D6356),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD0E8D8),
        onSecondaryContainer = Color(0xFF0A1F15),
        tertiary = Color(0xFF3C6472),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC0E9FA),
        onTertiaryContainer = Color(0xFF001F28),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF8FAF6),
        onBackground = Color(0xFF191C1A),
        surface = Color(0xFFF8FAF6),
        onSurface = Color(0xFF191C1A),
        surfaceContainer = Color(0xFFECEEEA),
        surfaceContainerLow = Color(0xFFF2F4F0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE7E9E5),
        surfaceContainerHighest = Color(0xFFE1E3DF),
        surfaceVariant = Color(0xFFE1E3DF),
        onSurfaceVariant = Color(0xFF444845),
        outline = Color(0xFF757874),
        outlineVariant = Color(0xFFC5C7C3),
        inverseOnSurface = Color(0xFFEFF1ED),
        inverseSurface = Color(0xFF2E312F),
        inversePrimary = Color(0xFF70DBA7),
        surfaceBright = Color(0xFFF8FAF6),
        surfaceDim = Color(0xFFD8DBD6),
        primaryFixed = Color(0xFF8DF7C2),
        primaryFixedDim = Color(0xFF70DBA7),
        onPrimaryFixed = Color(0xFF002113),
        onPrimaryFixedVariant = Color(0xFF005235),
        secondaryFixed = Color(0xFFD0E8D8),
        secondaryFixedDim = Color(0xFFB4CCBC),
        onSecondaryFixed = Color(0xFF0A1F15),
        onSecondaryFixedVariant = Color(0xFF364B3F),
        tertiaryFixed = Color(0xFFC0E9FA),
        tertiaryFixedDim = Color(0xFFA4CDDE),
        onTertiaryFixed = Color(0xFF001F28),
        onTertiaryFixedVariant = Color(0xFF234C5A),
    )

val DarkLightGreenTheme =
    darkColorScheme(
        primary = Color(0xFF70DBA7),
        onPrimary = Color(0xFF003824),
        primaryContainer = Color(0xFF005235),
        onPrimaryContainer = Color(0xFF8DF7C2),
        secondary = Color(0xFFB4CCBC),
        onSecondary = Color(0xFF20352A),
        secondaryContainer = Color(0xFF364B3F),
        onSecondaryContainer = Color(0xFFD0E8D8),
        tertiary = Color(0xFFA4CDDE),
        onTertiary = Color(0xFF063543),
        tertiaryContainer = Color(0xFF234C5A),
        onTertiaryContainer = Color(0xFFC0E9FA),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF111412),
        onBackground = Color(0xFFE1E3DF),
        surface = Color(0xFF111412),
        onSurface = Color(0xFFE1E3DF),
        surfaceContainer = Color(0xFF1D201E),
        surfaceContainerLow = Color(0xFF191C1A),
        surfaceContainerLowest = Color(0xFF0C0F0D),
        surfaceContainerHigh = Color(0xFF272B28),
        surfaceContainerHighest = Color(0xFF323633),
        surfaceVariant = Color(0xFF444845),
        onSurfaceVariant = Color(0xFFC5C7C3),
        outline = Color(0xFF8F918E),
        outlineVariant = Color(0xFF444845),
        inverseOnSurface = Color(0xFF2E312F),
        inverseSurface = Color(0xFFE1E3DF),
        inversePrimary = Color(0xFF006C48),
        surfaceBright = Color(0xFF373A37),
        surfaceDim = Color(0xFF111412),
        primaryFixed = Color(0xFF8DF7C2),
        primaryFixedDim = Color(0xFF70DBA7),
        onPrimaryFixed = Color(0xFF002113),
        onPrimaryFixedVariant = Color(0xFF005235),
        secondaryFixed = Color(0xFFD0E8D8),
        secondaryFixedDim = Color(0xFFB4CCBC),
        onSecondaryFixed = Color(0xFF0A1F15),
        onSecondaryFixedVariant = Color(0xFF364B3F),
        tertiaryFixed = Color(0xFFC0E9FA),
        tertiaryFixedDim = Color(0xFFA4CDDE),
        onTertiaryFixed = Color(0xFF001F28),
        onTertiaryFixedVariant = Color(0xFF234C5A),
    )
