package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightLimeTheme =
    lightColorScheme(
        primary = Color(0xFF5B6300),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDDED49),
        onPrimaryContainer = Color(0xFF1A1D00),
        secondary = Color(0xFF5E6044),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE4E5C1),
        onSecondaryContainer = Color(0xFF1B1D07),
        tertiary = Color(0xFF3C665A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBEECDC),
        onTertiaryContainer = Color(0xFF002019),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFCF9F0),
        onBackground = Color(0xFF1C1C17),
        surface = Color(0xFFFCF9F0),
        onSurface = Color(0xFF1C1C17),
        surfaceContainer = Color(0xFFF1EEE5),
        surfaceContainerLow = Color(0xFFF6F3EB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFEBE8DF),
        surfaceContainerHighest = Color(0xFFE5E2DA),
        surfaceVariant = Color(0xFFE5E2DA),
        onSurfaceVariant = Color(0xFF474741),
        outline = Color(0xFF787770),
        outlineVariant = Color(0xFFC9C6BE),
        inverseOnSurface = Color(0xFFF3F1E8),
        inverseSurface = Color(0xFF31312B),
        inversePrimary = Color(0xFFC1D02C),
        surfaceBright = Color(0xFFFCF9F0),
        surfaceDim = Color(0xFFDCDAD2),
        primaryFixed = Color(0xFFDDED49),
        primaryFixedDim = Color(0xFFC1D02C),
        onPrimaryFixed = Color(0xFF1A1D00),
        onPrimaryFixedVariant = Color(0xFF444B00),
        secondaryFixed = Color(0xFFE4E5C1),
        secondaryFixedDim = Color(0xFFC7C9A6),
        onSecondaryFixed = Color(0xFF1B1D07),
        onSecondaryFixedVariant = Color(0xFF46492E),
        tertiaryFixed = Color(0xFFBEECDC),
        tertiaryFixedDim = Color(0xFFA2D0C1),
        onTertiaryFixed = Color(0xFF002019),
        onTertiaryFixedVariant = Color(0xFF234E43),
    )

val DarkLimeTheme =
    darkColorScheme(
        primary = Color(0xFFC1D02C),
        onPrimary = Color(0xFF2F3300),
        primaryContainer = Color(0xFF444B00),
        onPrimaryContainer = Color(0xFFDDED49),
        secondary = Color(0xFFC7C9A6),
        onSecondary = Color(0xFF30321A),
        secondaryContainer = Color(0xFF46492E),
        onSecondaryContainer = Color(0xFFE4E5C1),
        tertiary = Color(0xFFA2D0C1),
        onTertiary = Color(0xFF07372D),
        tertiaryContainer = Color(0xFF234E43),
        onTertiaryContainer = Color(0xFFBEECDC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF13140F),
        onBackground = Color(0xFFE5E2DA),
        surface = Color(0xFF13140F),
        onSurface = Color(0xFFE5E2DA),
        surfaceContainer = Color(0xFF20201B),
        surfaceContainerLow = Color(0xFF1C1C17),
        surfaceContainerLowest = Color(0xFF0E0E0A),
        surfaceContainerHigh = Color(0xFF2A2A25),
        surfaceContainerHighest = Color(0xFF35352F),
        surfaceVariant = Color(0xFF474741),
        onSurfaceVariant = Color(0xFFC9C6BE),
        outline = Color(0xFF929189),
        outlineVariant = Color(0xFF474741),
        inverseOnSurface = Color(0xFF31312B),
        inverseSurface = Color(0xFFE5E2DA),
        inversePrimary = Color(0xFF5B6300),
        surfaceBright = Color(0xFF3A3934),
        surfaceDim = Color(0xFF13140F),
        primaryFixed = Color(0xFFDDED49),
        primaryFixedDim = Color(0xFFC1D02C),
        onPrimaryFixed = Color(0xFF1A1D00),
        onPrimaryFixedVariant = Color(0xFF444B00),
        secondaryFixed = Color(0xFFE4E5C1),
        secondaryFixedDim = Color(0xFFC7C9A6),
        onSecondaryFixed = Color(0xFF1B1D07),
        onSecondaryFixedVariant = Color(0xFF46492E),
        tertiaryFixed = Color(0xFFBEECDC),
        tertiaryFixedDim = Color(0xFFA2D0C1),
        onTertiaryFixed = Color(0xFF002019),
        onTertiaryFixedVariant = Color(0xFF234E43),
    )
