package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightOrangeTheme =
    lightColorScheme(
        primary = Color(0xFF8B5000),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDCBE),
        onPrimaryContainer = Color(0xFF2C1600),
        secondary = Color(0xFF725A42),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDCBE),
        onSecondaryContainer = Color(0xFF291806),
        tertiary = Color(0xFF58633A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFDCE8B4),
        onTertiaryContainer = Color(0xFF161E01),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F5),
        onBackground = Color(0xFF201B16),
        surface = Color(0xFFFFF8F5),
        onSurface = Color(0xFF201B16),
        surfaceContainer = Color(0xFFF7ECE4),
        surfaceContainerLow = Color(0xFFFDF2EA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF1E6DF),
        surfaceContainerHighest = Color(0xFFEBE0D9),
        surfaceVariant = Color(0xFFEBE0D9),
        onSurfaceVariant = Color(0xFF4C4640),
        outline = Color(0xFF7E7670),
        outlineVariant = Color(0xFFCFC5BE),
        inverseOnSurface = Color(0xFFFAEFE7),
        inverseSurface = Color(0xFF352F2B),
        inversePrimary = Color(0xFFFFB870),
        surfaceBright = Color(0xFFFFF8F5),
        surfaceDim = Color(0xFFE3D8D1),
        primaryFixed = Color(0xFFFFDCBE),
        primaryFixedDim = Color(0xFFFFB870),
        onPrimaryFixed = Color(0xFF2C1600),
        onPrimaryFixedVariant = Color(0xFF693C00),
        secondaryFixed = Color(0xFFFFDCBE),
        secondaryFixedDim = Color(0xFFE1C1A4),
        onSecondaryFixed = Color(0xFF291806),
        onSecondaryFixedVariant = Color(0xFF59422C),
        tertiaryFixed = Color(0xFFDCE8B4),
        tertiaryFixedDim = Color(0xFFC0CC9A),
        onTertiaryFixed = Color(0xFF161E01),
        onTertiaryFixedVariant = Color(0xFF414B24),
    )

val DarkOrangeTheme =
    darkColorScheme(
        primary = Color(0xFFFFB870),
        onPrimary = Color(0xFF4A2800),
        primaryContainer = Color(0xFF693C00),
        onPrimaryContainer = Color(0xFFFFDCBE),
        secondary = Color(0xFFE1C1A4),
        onSecondary = Color(0xFF402C18),
        secondaryContainer = Color(0xFF59422C),
        onSecondaryContainer = Color(0xFFFFDCBE),
        tertiary = Color(0xFFC0CC9A),
        onTertiary = Color(0xFF2B3410),
        tertiaryContainer = Color(0xFF414B24),
        onTertiaryContainer = Color(0xFFDCE8B4),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF17120E),
        onBackground = Color(0xFFEBE0D9),
        surface = Color(0xFF17120E),
        onSurface = Color(0xFFEBE0D9),
        surfaceContainer = Color(0xFF241F1A),
        surfaceContainerLow = Color(0xFF201B16),
        surfaceContainerLowest = Color(0xFF120D0A),
        surfaceContainerHigh = Color(0xFF2E2924),
        surfaceContainerHighest = Color(0xFF3A342F),
        surfaceVariant = Color(0xFF4C4640),
        onSurfaceVariant = Color(0xFFCFC5BE),
        outline = Color(0xFF988F89),
        outlineVariant = Color(0xFF4C4640),
        inverseOnSurface = Color(0xFF352F2B),
        inverseSurface = Color(0xFFEBE0D9),
        inversePrimary = Color(0xFF8B5000),
        surfaceBright = Color(0xFF3E3833),
        surfaceDim = Color(0xFF17120E),
        primaryFixed = Color(0xFFFFDCBE),
        primaryFixedDim = Color(0xFFFFB870),
        onPrimaryFixed = Color(0xFF2C1600),
        onPrimaryFixedVariant = Color(0xFF693C00),
        secondaryFixed = Color(0xFFFFDCBE),
        secondaryFixedDim = Color(0xFFE1C1A4),
        onSecondaryFixed = Color(0xFF291806),
        onSecondaryFixedVariant = Color(0xFF59422C),
        tertiaryFixed = Color(0xFFDCE8B4),
        tertiaryFixedDim = Color(0xFFC0CC9A),
        onTertiaryFixed = Color(0xFF161E01),
        onTertiaryFixedVariant = Color(0xFF414B24),
    )
