package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightPinkTheme =
    lightColorScheme(
        primary = Color(0xFFBC004B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DE),
        onPrimaryContainer = Color(0xFF400014),
        secondary = Color(0xFF75565B),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DE),
        onSecondaryContainer = Color(0xFF2C1519),
        tertiary = Color(0xFF795831),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDBA),
        onTertiaryContainer = Color(0xFF2B1700),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF201A1B),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF201A1B),
        surfaceContainer = Color(0xFFF8EBEB),
        surfaceContainerLow = Color(0xFFFDF1F1),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF2E5E6),
        surfaceContainerHighest = Color(0xFFECE0E0),
        surfaceVariant = Color(0xFFECE0E0),
        onSurfaceVariant = Color(0xFF4D4546),
        outline = Color(0xFF7E7575),
        outlineVariant = Color(0xFFCFC4C4),
        inverseOnSurface = Color(0xFFFBEEEE),
        inverseSurface = Color(0xFF362F2F),
        inversePrimary = Color(0xFFFFB2BE),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceDim = Color(0xFFE3D7D8),
        primaryFixed = Color(0xFFFFD9DE),
        primaryFixedDim = Color(0xFFFFB2BE),
        onPrimaryFixed = Color(0xFF400014),
        onPrimaryFixedVariant = Color(0xFF900038),
        secondaryFixed = Color(0xFFFFD9DE),
        secondaryFixedDim = Color(0xFFE5BDC2),
        onSecondaryFixed = Color(0xFF2C1519),
        onSecondaryFixedVariant = Color(0xFF5C3F43),
        tertiaryFixed = Color(0xFFFFDDBA),
        tertiaryFixedDim = Color(0xFFEBBF90),
        onTertiaryFixed = Color(0xFF2B1700),
        onTertiaryFixedVariant = Color(0xFF5F411C),
    )

val DarkPinkTheme =
    darkColorScheme(
        primary = Color(0xFFFFB2BE),
        onPrimary = Color(0xFF660025),
        primaryContainer = Color(0xFF900038),
        onPrimaryContainer = Color(0xFFFFD9DE),
        secondary = Color(0xFFE5BDC2),
        onSecondary = Color(0xFF43292D),
        secondaryContainer = Color(0xFF5C3F43),
        onSecondaryContainer = Color(0xFFFFD9DE),
        tertiary = Color(0xFFEBBF90),
        onTertiary = Color(0xFF452B08),
        tertiaryContainer = Color(0xFF5F411C),
        onTertiaryContainer = Color(0xFFFFDDBA),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF181213),
        onBackground = Color(0xFFECE0E0),
        surface = Color(0xFF181213),
        onSurface = Color(0xFFECE0E0),
        surfaceContainer = Color(0xFF241E1F),
        surfaceContainerLow = Color(0xFF201A1B),
        surfaceContainerLowest = Color(0xFF120D0D),
        surfaceContainerHigh = Color(0xFF2F2829),
        surfaceContainerHighest = Color(0xFF3A3334),
        surfaceVariant = Color(0xFF4D4546),
        onSurfaceVariant = Color(0xFFCFC4C4),
        outline = Color(0xFF988E8F),
        outlineVariant = Color(0xFF4D4546),
        inverseOnSurface = Color(0xFF362F2F),
        inverseSurface = Color(0xFFECE0E0),
        inversePrimary = Color(0xFFBC004B),
        surfaceBright = Color(0xFF3F3738),
        surfaceDim = Color(0xFF181213),
        primaryFixed = Color(0xFFFFD9DE),
        primaryFixedDim = Color(0xFFFFB2BE),
        onPrimaryFixed = Color(0xFF400014),
        onPrimaryFixedVariant = Color(0xFF900038),
        secondaryFixed = Color(0xFFFFD9DE),
        secondaryFixedDim = Color(0xFFE5BDC2),
        onSecondaryFixed = Color(0xFF2C1519),
        onSecondaryFixedVariant = Color(0xFF5C3F43),
        tertiaryFixed = Color(0xFFFFDDBA),
        tertiaryFixedDim = Color(0xFFEBBF90),
        onTertiaryFixed = Color(0xFF2B1700),
        onTertiaryFixedVariant = Color(0xFF5F411C),
    )
