package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF7B4E7F)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFD6FE)
private val onPrimaryContainerLight = Color(0xFF613766)
private val secondaryLight = Color(0xFF6B586B)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFF4DBF1)
private val onSecondaryContainerLight = Color(0xFF534153)
private val tertiaryLight = Color(0xFF82524A)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDAD4)
private val onTertiaryContainerLight = Color(0xFF673B34)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF7FA)
private val onBackgroundLight = Color(0xFF1F1A1F)
private val surfaceLight = Color(0xFFFFF7FA)
private val onSurfaceLight = Color(0xFF1F1A1F)
private val surfaceVariantLight = Color(0xFFECDFE8)
private val onSurfaceVariantLight = Color(0xFF4D444C)
private val outlineLight = Color(0xFF7F747D)
private val outlineVariantLight = Color(0xFFD0C3CC)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF352F34)
private val inverseOnSurfaceLight = Color(0xFFF9EEF5)
private val inversePrimaryLight = Color(0xFFEBB5ED)
private val surfaceDimLight = Color(0xFFE2D7DE)
private val surfaceBrightLight = Color(0xFFFFF7FA)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFCF0F7)
private val surfaceContainerLight = Color(0xFFF6EBF2)
private val surfaceContainerHighLight = Color(0xFFF0E5EC)
private val surfaceContainerHighestLight = Color(0xFFEBDFE6)

private val primaryLightHighContrast = Color(0xFF441C49)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF643969)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF372737)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF554355)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF47211B)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF693D36)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF7FA)
private val onBackgroundLightHighContrast = Color(0xFF1F1A1F)
private val surfaceLightHighContrast = Color(0xFFFFF7FA)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFECDFE8)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF312A31)
private val outlineVariantLightHighContrast = Color(0xFF4F464E)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF352F34)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFEBB5ED)
private val surfaceDimLightHighContrast = Color(0xFFC0B6BD)
private val surfaceBrightLightHighContrast = Color(0xFFFFF7FA)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF9EEF5)
private val surfaceContainerLightHighContrast = Color(0xFFEBDFE6)
private val surfaceContainerHighLightHighContrast = Color(0xFFDCD1D8)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCEC4CA)

private val primaryDark = Color(0xFFEBB5ED)
private val onPrimaryDark = Color(0xFF49204E)
private val primaryContainerDark = Color(0xFF613766)
private val onPrimaryContainerDark = Color(0xFFFFD6FE)
private val secondaryDark = Color(0xFFD7BFD5)
private val onSecondaryDark = Color(0xFF3B2B3C)
private val secondaryContainerDark = Color(0xFF534153)
private val onSecondaryContainerDark = Color(0xFFF4DBF1)
private val tertiaryDark = Color(0xFFF6B8AD)
private val onTertiaryDark = Color(0xFF4C251F)
private val tertiaryContainerDark = Color(0xFF673B34)
private val onTertiaryContainerDark = Color(0xFFFFDAD4)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF171216)
private val onBackgroundDark = Color(0xFFEBDFE6)
private val surfaceDark = Color(0xFF171216)
private val onSurfaceDark = Color(0xFFEBDFE6)
private val surfaceVariantDark = Color(0xFF4D444C)
private val onSurfaceVariantDark = Color(0xFFD0C3CC)
private val outlineDark = Color(0xFF998D96)
private val outlineVariantDark = Color(0xFF4D444C)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEBDFE6)
private val inverseOnSurfaceDark = Color(0xFF352F34)
private val inversePrimaryDark = Color(0xFF7B4E7F)
private val surfaceDimDark = Color(0xFF171216)
private val surfaceBrightDark = Color(0xFF3E373D)
private val surfaceContainerLowestDark = Color(0xFF110D11)
private val surfaceContainerLowDark = Color(0xFF1F1A1F)
private val surfaceContainerDark = Color(0xFF231E23)
private val surfaceContainerHighDark = Color(0xFF2E282D)
private val surfaceContainerHighestDark = Color(0xFF393338)

private val primaryDarkHighContrast = Color(0xFFFFEAFB)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFE7B1E9)
private val onPrimaryContainerDarkHighContrast = Color(0xFF1B0021)
private val secondaryDarkHighContrast = Color(0xFFFFEAFB)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFD3BBD1)
private val onSecondaryContainerDarkHighContrast = Color(0xFF130715)
private val tertiaryDarkHighContrast = Color(0xFFFFECE9)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFF1B4AA)
private val onTertiaryContainerDarkHighContrast = Color(0xFF1E0302)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF171216)
private val onBackgroundDarkHighContrast = Color(0xFFEBDFE6)
private val surfaceDarkHighContrast = Color(0xFF171216)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4D444C)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFFAECF6)
private val outlineVariantDarkHighContrast = Color(0xFFCCBFC8)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEBDFE6)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF633867)
private val surfaceDimDarkHighContrast = Color(0xFF171216)
private val surfaceBrightDarkHighContrast = Color(0xFF554E54)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF231E23)
private val surfaceContainerDarkHighContrast = Color(0xFF352F34)
private val surfaceContainerHighDarkHighContrast = Color(0xFF40393F)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4C454A)

val LightPurpleTheme =
    lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

val DarkPurpleTheme =
    darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

val HighContrastLightPurpleTheme =
    lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

val HighContrastDarkPurpleTheme =
    darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
