package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightPurpleTheme =
    lightColorScheme(
        primary = Color(0xFF9A25AE),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD6FE),
        onPrimaryContainer = Color(0xFF35003F),
        secondary = Color(0xFF6B586B),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF4DBF1),
        onSecondaryContainer = Color(0xFF251626),
        tertiary = Color(0xFF82524A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDAD4),
        onTertiaryContainer = Color(0xFF33110C),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF7FA),
        onBackground = Color(0xFF1E1A1D),
        surface = Color(0xFFFFF7FA),
        onSurface = Color(0xFF1E1A1D),
        surfaceContainer = Color(0xFFF4ECF0),
        surfaceContainerLow = Color(0xFFFAF1F5),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFEEE6EA),
        surfaceContainerHighest = Color(0xFFE9E0E4),
        surfaceVariant = Color(0xFFE9E0E4),
        onSurfaceVariant = Color(0xFF4A4549),
        outline = Color(0xFF7B7579),
        outlineVariant = Color(0xFFCCC4C8),
        inverseOnSurface = Color(0xFFF7EEF3),
        inverseSurface = Color(0xFF332F32),
        inversePrimary = Color(0xFFF9ABFF),
        surfaceBright = Color(0xFFFFF7FA),
        surfaceDim = Color(0xFFE0D8DC),
        primaryFixed = Color(0xFFFFD6FE),
        primaryFixedDim = Color(0xFFF9ABFF),
        onPrimaryFixed = Color(0xFF35003F),
        onPrimaryFixedVariant = Color(0xFF7B008F),
        secondaryFixed = Color(0xFFF4DBF1),
        secondaryFixedDim = Color(0xFFD7BFD5),
        onSecondaryFixed = Color(0xFF251626),
        onSecondaryFixedVariant = Color(0xFF534153),
        tertiaryFixed = Color(0xFFFFDAD4),
        tertiaryFixedDim = Color(0xFFF6B8AD),
        onTertiaryFixed = Color(0xFF33110C),
        onTertiaryFixedVariant = Color(0xFF673B34),
    )

val DarkPurpleTheme =
    darkColorScheme(
        primary = Color(0xFFF9ABFF),
        onPrimary = Color(0xFF570066),
        primaryContainer = Color(0xFF7B008F),
        onPrimaryContainer = Color(0xFFFFD6FE),
        secondary = Color(0xFFD7BFD5),
        onSecondary = Color(0xFF3B2B3C),
        secondaryContainer = Color(0xFF534153),
        onSecondaryContainer = Color(0xFFF4DBF1),
        tertiary = Color(0xFFF6B8AD),
        onTertiary = Color(0xFF4C251F),
        tertiaryContainer = Color(0xFF673B34),
        onTertiaryContainer = Color(0xFFFFDAD4),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF161215),
        onBackground = Color(0xFFE9E0E4),
        surface = Color(0xFF161215),
        onSurface = Color(0xFFE9E0E4),
        surfaceContainer = Color(0xFF221E22),
        surfaceContainerLow = Color(0xFF1E1A1D),
        surfaceContainerLowest = Color(0xFF100D10),
        surfaceContainerHigh = Color(0xFF2D292C),
        surfaceContainerHighest = Color(0xFF383337),
        surfaceVariant = Color(0xFF4A4549),
        onSurfaceVariant = Color(0xFFCCC4C8),
        outline = Color(0xFF958F93),
        outlineVariant = Color(0xFF4A4549),
        inverseOnSurface = Color(0xFF332F32),
        inverseSurface = Color(0xFFE9E0E4),
        inversePrimary = Color(0xFF9A25AE),
        surfaceBright = Color(0xFF3C383B),
        surfaceDim = Color(0xFF161215),
        primaryFixed = Color(0xFFFFD6FE),
        primaryFixedDim = Color(0xFFF9ABFF),
        onPrimaryFixed = Color(0xFF35003F),
        onPrimaryFixedVariant = Color(0xFF7B008F),
        secondaryFixed = Color(0xFFF4DBF1),
        secondaryFixedDim = Color(0xFFD7BFD5),
        onSecondaryFixed = Color(0xFF251626),
        onSecondaryFixedVariant = Color(0xFF534153),
        tertiaryFixed = Color(0xFFFFDAD4),
        tertiaryFixedDim = Color(0xFFF6B8AD),
        onTertiaryFixed = Color(0xFF33110C),
        onTertiaryFixedVariant = Color(0xFF673B34),
    )
