package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightRedTheme =
    lightColorScheme(
        primary = Color(0xFFBB1614),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD5),
        onPrimaryContainer = Color(0xFF410001),
        secondary = Color(0xFF775652),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDAD5),
        onSecondaryContainer = Color(0xFF2C1512),
        tertiary = Color(0xFF705C2E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFCDFA6),
        onTertiaryContainer = Color(0xFF261A00),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF201A19),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF201A19),
        surfaceContainer = Color(0xFFF8EBE9),
        surfaceContainerLow = Color(0xFFFEF1EF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF3E5E3),
        surfaceContainerHighest = Color(0xFFEDE0DE),
        surfaceVariant = Color(0xFFEDE0DE),
        onSurfaceVariant = Color(0xFF4D4544),
        outline = Color(0xFF7F7573),
        outlineVariant = Color(0xFFD0C4C2),
        inverseOnSurface = Color(0xFFFBEEEC),
        inverseSurface = Color(0xFF362F2E),
        inversePrimary = Color(0xFFFFB4A9),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceDim = Color(0xFFE4D7D5),
        primaryFixed = Color(0xFFFFDAD5),
        primaryFixedDim = Color(0xFFFFB4A9),
        onPrimaryFixed = Color(0xFF410001),
        onPrimaryFixedVariant = Color(0xFF930005),
        secondaryFixed = Color(0xFFFFDAD5),
        secondaryFixedDim = Color(0xFFE7BDB7),
        onSecondaryFixed = Color(0xFF2C1512),
        onSecondaryFixedVariant = Color(0xFF5D3F3B),
        tertiaryFixed = Color(0xFFFCDFA6),
        tertiaryFixedDim = Color(0xFFDFC38C),
        onTertiaryFixed = Color(0xFF261A00),
        onTertiaryFixedVariant = Color(0xFF574419),
    )

val DarkRedTheme =
    darkColorScheme(
        primary = Color(0xFFFFB4A9),
        onPrimary = Color(0xFF690002),
        primaryContainer = Color(0xFF930005),
        onPrimaryContainer = Color(0xFFFFDAD5),
        secondary = Color(0xFFE7BDB7),
        onSecondary = Color(0xFF442926),
        secondaryContainer = Color(0xFF5D3F3B),
        onSecondaryContainer = Color(0xFFFFDAD5),
        tertiary = Color(0xFFDFC38C),
        onTertiary = Color(0xFF3E2E04),
        tertiaryContainer = Color(0xFF574419),
        onTertiaryContainer = Color(0xFFFCDFA6),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF181211),
        onBackground = Color(0xFFEDE0DE),
        surface = Color(0xFF181211),
        onSurface = Color(0xFFEDE0DE),
        surfaceContainer = Color(0xFF251E1D),
        surfaceContainerLow = Color(0xFF201A19),
        surfaceContainerLowest = Color(0xFF120D0C),
        surfaceContainerHigh = Color(0xFF2F2827),
        surfaceContainerHighest = Color(0xFF3B3332),
        surfaceVariant = Color(0xFF4D4544),
        onSurfaceVariant = Color(0xFFD0C4C2),
        outline = Color(0xFF998E8D),
        outlineVariant = Color(0xFF4D4544),
        inverseOnSurface = Color(0xFF362F2E),
        inverseSurface = Color(0xFFEDE0DE),
        inversePrimary = Color(0xFFBB1614),
        surfaceBright = Color(0xFF3F3736),
        surfaceDim = Color(0xFF181211),
        primaryFixed = Color(0xFFFFDAD5),
        primaryFixedDim = Color(0xFFFFB4A9),
        onPrimaryFixed = Color(0xFF410001),
        onPrimaryFixedVariant = Color(0xFF930005),
        secondaryFixed = Color(0xFFFFDAD5),
        secondaryFixedDim = Color(0xFFE7BDB7),
        onSecondaryFixed = Color(0xFF2C1512),
        onSecondaryFixedVariant = Color(0xFF5D3F3B),
        tertiaryFixed = Color(0xFFFCDFA6),
        tertiaryFixedDim = Color(0xFFDFC38C),
        onTertiaryFixed = Color(0xFF261A00),
        onTertiaryFixedVariant = Color(0xFF574419),
    )
