package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightSakuraTheme =
    lightColorScheme(
        primary = Color(0xFF9B404F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DC),
        onPrimaryContainer = Color(0xFF400011),
        secondary = Color(0xFF765659),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DC),
        onSecondaryContainer = Color(0xFF2C1518),
        tertiary = Color(0xFF785830),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDB7),
        onTertiaryContainer = Color(0xFF2A1700),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF201A1A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF201A1A),
        surfaceContainer = Color(0xFFF8EBEB),
        surfaceContainerLow = Color(0xFFFEF1F1),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF2E5E5),
        surfaceContainerHighest = Color(0xFFECE0E0),
        surfaceVariant = Color(0xFFECE0E0),
        onSurfaceVariant = Color(0xFF4D4545),
        outline = Color(0xFF7E7575),
        outlineVariant = Color(0xFFD0C4C4),
        inverseOnSurface = Color(0xFFFBEEEE),
        inverseSurface = Color(0xFF362F2F),
        inversePrimary = Color(0xFFFFB2BA),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceDim = Color(0xFFE4D7D7),
        primaryFixed = Color(0xFFFFD9DC),
        primaryFixedDim = Color(0xFFFFB2BA),
        onPrimaryFixed = Color(0xFF400011),
        onPrimaryFixedVariant = Color(0xFF7D2939),
        secondaryFixed = Color(0xFFFFD9DC),
        secondaryFixedDim = Color(0xFFE5BDC0),
        onSecondaryFixed = Color(0xFF2C1518),
        onSecondaryFixedVariant = Color(0xFF5C3F42),
        tertiaryFixed = Color(0xFFFFDDB7),
        tertiaryFixedDim = Color(0xFFE9BF8F),
        onTertiaryFixed = Color(0xFF2A1700),
        onTertiaryFixedVariant = Color(0xFF5E411B),
    )

val DarkSakuraTheme =
    darkColorScheme(
        primary = Color(0xFFFFB2BA),
        onPrimary = Color(0xFF5F1223),
        primaryContainer = Color(0xFF7D2939),
        onPrimaryContainer = Color(0xFFFFD9DC),
        secondary = Color(0xFFE5BDC0),
        onSecondary = Color(0xFF43292C),
        secondaryContainer = Color(0xFF5C3F42),
        onSecondaryContainer = Color(0xFFFFD9DC),
        tertiary = Color(0xFFE9BF8F),
        onTertiary = Color(0xFF442B07),
        tertiaryContainer = Color(0xFF5E411B),
        onTertiaryContainer = Color(0xFFFFDDB7),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF181212),
        onBackground = Color(0xFFECE0E0),
        surface = Color(0xFF181212),
        onSurface = Color(0xFFECE0E0),
        surfaceContainer = Color(0xFF241E1E),
        surfaceContainerLow = Color(0xFF201A1A),
        surfaceContainerLowest = Color(0xFF120D0D),
        surfaceContainerHigh = Color(0xFF2F2829),
        surfaceContainerHighest = Color(0xFF3A3333),
        surfaceVariant = Color(0xFF4D4545),
        onSurfaceVariant = Color(0xFFD0C4C4),
        outline = Color(0xFF998E8F),
        outlineVariant = Color(0xFF4D4545),
        inverseOnSurface = Color(0xFF362F2F),
        inverseSurface = Color(0xFFECE0E0),
        inversePrimary = Color(0xFF9B404F),
        surfaceBright = Color(0xFF3F3738),
        surfaceDim = Color(0xFF181212),
        primaryFixed = Color(0xFFFFD9DC),
        primaryFixedDim = Color(0xFFFFB2BA),
        onPrimaryFixed = Color(0xFF400011),
        onPrimaryFixedVariant = Color(0xFF7D2939),
        secondaryFixed = Color(0xFFFFD9DC),
        secondaryFixedDim = Color(0xFFE5BDC0),
        onSecondaryFixed = Color(0xFF2C1518),
        onSecondaryFixedVariant = Color(0xFF5C3F42),
        tertiaryFixed = Color(0xFFFFDDB7),
        tertiaryFixedDim = Color(0xFFE9BF8F),
        onTertiaryFixed = Color(0xFF2A1700),
        onTertiaryFixedVariant = Color(0xFF5E411B),
    )
