package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightTealTheme =
    lightColorScheme(
        primary = Color(0xFF006A60),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF74F8E5),
        onPrimaryContainer = Color(0xFF00201C),
        secondary = Color(0xFF4A635F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCCE8E2),
        onSecondaryContainer = Color(0xFF05201C),
        tertiary = Color(0xFF456179),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCCE5FF),
        onTertiaryContainer = Color(0xFF001E31),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF7FAF8),
        onBackground = Color(0xFF191C1B),
        surface = Color(0xFFF7FAF8),
        onSurface = Color(0xFF191C1B),
        surfaceContainer = Color(0xFFECEEEC),
        surfaceContainerLow = Color(0xFFF2F4F2),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFE6E9E7),
        surfaceContainerHighest = Color(0xFFE0E3E1),
        surfaceVariant = Color(0xFFE0E3E1),
        onSurfaceVariant = Color(0xFF444746),
        outline = Color(0xFF747876),
        outlineVariant = Color(0xFFC4C7C5),
        inverseOnSurface = Color(0xFFEFF1EF),
        inverseSurface = Color(0xFF2D3130),
        inversePrimary = Color(0xFF53DBC9),
        surfaceBright = Color(0xFFF7FAF8),
        surfaceDim = Color(0xFFD8DBD9),
        primaryFixed = Color(0xFF74F8E5),
        primaryFixedDim = Color(0xFF53DBC9),
        onPrimaryFixed = Color(0xFF00201C),
        onPrimaryFixedVariant = Color(0xFF005048),
        secondaryFixed = Color(0xFFCCE8E2),
        secondaryFixedDim = Color(0xFFB1CCC6),
        onSecondaryFixed = Color(0xFF05201C),
        onSecondaryFixedVariant = Color(0xFF334B47),
        tertiaryFixed = Color(0xFFCCE5FF),
        tertiaryFixedDim = Color(0xFFADCAE6),
        onTertiaryFixed = Color(0xFF001E31),
        onTertiaryFixedVariant = Color(0xFF2D4961),
    )

val DarkTealTheme =
    darkColorScheme(
        primary = Color(0xFF53DBC9),
        onPrimary = Color(0xFF003731),
        primaryContainer = Color(0xFF005048),
        onPrimaryContainer = Color(0xFF74F8E5),
        secondary = Color(0xFFB1CCC6),
        onSecondary = Color(0xFF1C3531),
        secondaryContainer = Color(0xFF334B47),
        onSecondaryContainer = Color(0xFFCCE8E2),
        tertiary = Color(0xFFADCAE6),
        onTertiary = Color(0xFF153349),
        tertiaryContainer = Color(0xFF2D4961),
        onTertiaryContainer = Color(0xFFCCE5FF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF101413),
        onBackground = Color(0xFFE0E3E1),
        surface = Color(0xFF101413),
        onSurface = Color(0xFFE0E3E1),
        surfaceContainer = Color(0xFF1D201F),
        surfaceContainerLow = Color(0xFF191C1B),
        surfaceContainerLowest = Color(0xFF0B0F0E),
        surfaceContainerHigh = Color(0xFF272B2A),
        surfaceContainerHighest = Color(0xFF323534),
        surfaceVariant = Color(0xFF444746),
        onSurfaceVariant = Color(0xFFC4C7C5),
        outline = Color(0xFF8E9190),
        outlineVariant = Color(0xFF444746),
        inverseOnSurface = Color(0xFF2D3130),
        inverseSurface = Color(0xFFE0E3E1),
        inversePrimary = Color(0xFF006A60),
        surfaceBright = Color(0xFF363A39),
        surfaceDim = Color(0xFF101413),
        primaryFixed = Color(0xFF74F8E5),
        primaryFixedDim = Color(0xFF53DBC9),
        onPrimaryFixed = Color(0xFF00201C),
        onPrimaryFixedVariant = Color(0xFF005048),
        secondaryFixed = Color(0xFFCCE8E2),
        secondaryFixedDim = Color(0xFFB1CCC6),
        onSecondaryFixed = Color(0xFF05201C),
        onSecondaryFixedVariant = Color(0xFF334B47),
        tertiaryFixed = Color(0xFFCCE5FF),
        tertiaryFixedDim = Color(0xFFADCAE6),
        onTertiaryFixed = Color(0xFF001E31),
        onTertiaryFixedVariant = Color(0xFF2D4961),
    )
