package com.h3110w0r1d.t9launcher.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightYellowTheme =
    lightColorScheme(
        primary = Color(0xFF695F00),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFF9E534),
        onPrimaryContainer = Color(0xFF201C00),
        secondary = Color(0xFF645F41),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEBE3BD),
        onSecondaryContainer = Color(0xFF1F1C05),
        tertiary = Color(0xFF406652),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC2ECD3),
        onTertiaryContainer = Color(0xFF002113),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFEF9F0),
        onBackground = Color(0xFF1D1C16),
        surface = Color(0xFFFEF9F0),
        onSurface = Color(0xFF1D1C16),
        surfaceContainer = Color(0xFFF2EDE4),
        surfaceContainerLow = Color(0xFFF8F3EA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFECE8DF),
        surfaceContainerHighest = Color(0xFFE7E2D9),
        surfaceVariant = Color(0xFFE7E2D9),
        onSurfaceVariant = Color(0xFF494740),
        outline = Color(0xFF7A776F),
        outlineVariant = Color(0xFFCAC6BD),
        inverseOnSurface = Color(0xFFF5F0E7),
        inverseSurface = Color(0xFF32302A),
        inversePrimary = Color(0xFFDBC90A),
        surfaceBright = Color(0xFFFEF9F0),
        surfaceDim = Color(0xFFDEDAD1),
        primaryFixed = Color(0xFFF9E534),
        primaryFixedDim = Color(0xFFDBC90A),
        onPrimaryFixed = Color(0xFF201C00),
        onPrimaryFixedVariant = Color(0xFF4F4800),
        secondaryFixed = Color(0xFFEBE3BD),
        secondaryFixedDim = Color(0xFFCEC7A3),
        onSecondaryFixed = Color(0xFF1F1C05),
        onSecondaryFixedVariant = Color(0xFF4B472B),
        tertiaryFixed = Color(0xFFC2ECD3),
        tertiaryFixedDim = Color(0xFFA7D0B7),
        onTertiaryFixed = Color(0xFF002113),
        onTertiaryFixedVariant = Color(0xFF294E3B),
    )

val DarkYellowTheme =
    darkColorScheme(
        primary = Color(0xFFDBC90A),
        onPrimary = Color(0xFF363100),
        primaryContainer = Color(0xFF4F4800),
        onPrimaryContainer = Color(0xFFF9E534),
        secondary = Color(0xFFCEC7A3),
        onSecondary = Color(0xFF343117),
        secondaryContainer = Color(0xFF4B472B),
        onSecondaryContainer = Color(0xFFEBE3BD),
        tertiary = Color(0xFFA7D0B7),
        onTertiary = Color(0xFF103726),
        tertiaryContainer = Color(0xFF294E3B),
        onTertiaryContainer = Color(0xFFC2ECD3),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF14130E),
        onBackground = Color(0xFFE7E2D9),
        surface = Color(0xFF14130E),
        onSurface = Color(0xFFE7E2D9),
        surfaceContainer = Color(0xFF21201A),
        surfaceContainerLow = Color(0xFF1D1C16),
        surfaceContainerLowest = Color(0xFF0F0E09),
        surfaceContainerHigh = Color(0xFF2B2A24),
        surfaceContainerHighest = Color(0xFF36352F),
        surfaceVariant = Color(0xFF494740),
        onSurfaceVariant = Color(0xFFCAC6BD),
        outline = Color(0xFF949089),
        outlineVariant = Color(0xFF494740),
        inverseOnSurface = Color(0xFF32302A),
        inverseSurface = Color(0xFFE7E2D9),
        inversePrimary = Color(0xFF695F00),
        surfaceBright = Color(0xFF3B3933),
        surfaceDim = Color(0xFF14130E),
        primaryFixed = Color(0xFFF9E534),
        primaryFixedDim = Color(0xFFDBC90A),
        onPrimaryFixed = Color(0xFF201C00),
        onPrimaryFixedVariant = Color(0xFF4F4800),
        secondaryFixed = Color(0xFFEBE3BD),
        secondaryFixedDim = Color(0xFFCEC7A3),
        onSecondaryFixed = Color(0xFF1F1C05),
        onSecondaryFixedVariant = Color(0xFF4B472B),
        tertiaryFixed = Color(0xFFC2ECD3),
        tertiaryFixedDim = Color(0xFFA7D0B7),
        onTertiaryFixed = Color(0xFF002113),
        onTertiaryFixedVariant = Color(0xFF294E3B),
    )
