name: Release Xposed
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-xposed"

jobs:
  merge-build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin xposed

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Merge main into xposed
        run: |
          git checkout xposed
          git pull origin xposed
          git merge ${{ env.TAG_NAME }} -m "Auto merge from main via tag ${{ env.TAG_NAME }}"
          git push origin xposed

      - name: Create and push xposed tag
        run: |
          VERSION_TAG=${{ env.TAG_NAME }}
          if [[ $VERSION_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            XPOSED_TAG="$VERSION_TAG-xposed"
            echo "Creating and pushing new tag: $XPOSED_TAG"
            git tag $XPOSED_TAG
            git push origin $XPOSED_TAG
          else
            echo "Tag does not match pattern vX.X.X. Skipping xposed tag creation."
          fi

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK (Xposed)
        run: ./gradlew assembleXposedRelease

      - name: Sign APK (Xposed)
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/xposed/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Signed APK to Release (Xposed)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/xposed/release/*-signed.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          tag: ${{ env.TAG_NAME }}-xposed
